server:
  port: 8007
dubbo:
  application:
    name: DriverApplication
    serialize-check-status: DISABLE
  protocol:
    name: tri
    port: 50052
  registry:
    address: nacos://127.0.0.1:8848?register-consumer-url=true
    register-mode: instance
    file: ./registrycache
    file-cache: false
  consumer:
    check: false

spring:
  application:
    name: driver